In [1]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics-With-Python-CompleteGuide/refs/heads/main/clead_google_playstore_data.csv")

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     9476 non-null   object
 13  day             10840 non-null  int64
 14  month           10840 non-null  int64
 15  year            10840 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.3+ MB

In [3]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4,20,6,2018

In [4]:
data.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
10835,Sya9a Maroc - FR,FAMILY,4.5,38,53000.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1,25,7,2017
10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3600.0,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1,6,7,2018
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9500.0,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2,20,1,2017
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,NaN,19,1,2015
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,NaN,25,7,2018

In [7]:
data.shape

(10840, 16)

In [8]:
data.describe()

,Rating,Reviews,Size,Installs,Price,day,month,year
count,9366.000000,1.084000e+04,9145.000000,1.084000e+04,10840.000000,10840.000000,10840.000000,10840.000000
mean,4.191757,4.441529e+05,21506.534062,1.546434e+07,1.027368,15.609041,6.422325,2017.399723
std,0.515219,2.927761e+06,22596.020795,8.502936e+07,15.949703,9.561621,2.578388,1.100914
min,1.000000,0.000000e+00,10.000000,0.000000e+00,0.000000,1.000000,1.000000,2010.000000
25%,4.000000,3.800000e+01,4900.000000,1.000000e+03,0.000000,6.000000,5.000000,2017.000000
50%,4.300000,2.094000e+03,13000.000000,1.000000e+05,0.000000,16.000000,7.000000,2018.000000
75%,4.500000,5.477550e+04,30000.000000,5.000000e+06,0.000000,24.000000,8.000000,2018.000000
max,5.000000,7.815831e+07,100000.000000,1.000000e+09,400.000000,31.000000,12.000000,2018.000000

In [9]:
data.describe(include='all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
count,10840,10840,9366.000000,1.084000e+04,9145.000000,1.084000e+04,10839,10840.000000,10840,10840,10840,10832,9476,10840.000000,10840.000000,10840.000000
unique,9659,33,NaN,NaN,NaN,NaN,2,NaN,6,119,1377,2831,32,NaN,NaN,NaN
top,ROBLOX,FAMILY,NaN,NaN,NaN,NaN,Free,NaN,Everyone,Tools,2018-08-03,Varies with device,4.1,NaN,NaN,NaN
freq,9,1972,NaN,NaN,NaN,NaN,10039,NaN,8714,842,326,1459,2451,NaN,NaN,NaN
mean,NaN,NaN,4.191757,4.441529e+05,21506.534062,1.546434e+07,NaN,1.027368,NaN,NaN,NaN,NaN,NaN,15.609041,6.422325,2017.399723
std,NaN,NaN,0.515219,2.927761e+06,22596.020795,8.502936e+07,NaN,15.949703,NaN,NaN,NaN,NaN,NaN,9.561621,2.578388,1.100914
min,NaN,NaN,1.000000,0.000000e+00,10.000000,0.000000e+00,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,2010.000000
25%,NaN,NaN,4.000000,3.800000e+01,4900.000000,1.000000e+03,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,2017.000000
50%,NaN,NaN,4.300000,2.094000e+03,13000.000000,1.000000e+05,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,16.000000,7.000000,2018.000000
75%,NaN,NaN,4.500000,5.477550e+04,30000.000000,5.000000e+06,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,24.000000,8.000000,2018.000000
max,NaN,NaN,5.000000,7.815831e+07,100000.000000,1.000000e+09,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,31.000000,12.000000,2018.000000

In [10]:
# Find Duplicates
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10835    False
10836    False
10837    False
10838    False
10839    False
Length: 10840, dtype: bool

In [11]:
# view duplicates
data[data.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,NaN,5000000,Free,0.0,Everyone,Business,2018-02-26,Varies with device,4.0.3,26,2,2018
236,Box,BUSINESS,4.2,159872,NaN,10000000,Free,0.0,Everyone,Business,2018-07-31,Varies with device,NaN,31,7,2018
239,Google My Business,BUSINESS,4.4,70991,NaN,5000000,Free,0.0,Everyone,Business,2018-07-24,2.19.0.204537701,4.4,24,7,2018
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37000.0,10000000,Free,0.0,Everyone,Business,2018-07-20,4.1.28165.0716,4.0,20,7,2018
261,join.me - Simple Meetings,BUSINESS,4.0,6989,NaN,1000000,Free,0.0,Everyone,Business,2018-07-16,4.3.0.508,4.4,16,7,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,NaN,10000000,Free,0.0,Everyone,Productivity,2018-04-06,Varies with device,NaN,6,4,2018
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,NaN,1000000,Free,0.0,Everyone,Productivity,2018-08-06,Varies with device,NaN,6,8,2018
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,NaN,100000000,Free,0.0,Everyone,Productivity,2018-06-27,Varies with device,NaN,27,6,2018
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86000.0,10000,Free,0.0,Everyone,Medical,2018-06-01,0.6.88,5.0,1,6,2018
10767,AAFP,MEDICAL,3.8,63,24000.0,10000,Free,0.0,Everyone,Medical,2018-06-22,2.3.1,5.0,22,6,2018

what needs to be done

Find Uniques, Find Duplicates,Fixing data types ,correct data size and column as well,correct install columns, correct price column

In [17]:
data['App'].unique()

array(['Photo Editor & Candy Camera & Grid & ScrapBook',
       'Coloring book moana',
       'U Launcher Lite – FREE Live Cool Themes, Hide Apps', ...,
       'Parkinson Exercices FR', 'The SCP Foundation DB fr nn5n',
       'iHoroscope - 2018 Daily Horoscope & Astrology'],
      shape=(9659,), dtype=object)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     9476 non-null   object
 13  day             10840 non-null  int64
 14  month           10840 non-null  int64
 15  year            10840 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.3+ MB

In [ ]:
data['Reviews']

0           159
1           967
2         87510
3        215644
4           967
          ...
10835        38
10836         4
10837         3
10838       114
10839    398307
Name: Reviews, Length: 10840, dtype: int64

In [23]:
data['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10835    4.5
10836    5.0
10837    NaN
10838    4.5
10839    4.5
Name: Rating, Length: 10840, dtype: float64